import express from "express";
import jwt from "jsonwebtoken";
import CampaignTemplate from "../models/CampaignTemplate.js";
import Campaign from "../models/Campaign.js";
import Audience from "../models/Audience.js";
import EmailTracking from "../models/EmailTracking.js";
import { sendCampaignEmail, wrapLinksWithTracking } from "../services/emailService.js";
import { seedCampaignTemplates, createDefaultAudiences, markCampaignSent } from "../services/campaignAutomation.js";

const router = express.Router();
const FRONTEND_URL = process.env.FRONTEND_URL || "https://www.thetechfestival.com";
const API_URL = process.env.API_URL || "https://techfest-canada-backend.onrender.com";

const authMiddleware = async (req, res, next) => {
  try {
    const header = req.headers.authorization;
    if (!header || !header.startsWith("Bearer ")) {
      return res.status(401).json({ error: "No token provided" });
    }
    const token = header.split(" ")[1];
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    req.user = decoded;
    next();
  } catch {
    return res.status(401).json({ error: "Invalid token" });
  }
};

const adminMiddleware = (req, res, next) => {
  if (req.user?.role !== "admin") {
    return res.status(403).json({ error: "Admin access required" });
  }
  next();
};

// Helper: Wrap HTML with proper email structure
function wrapEmailHtml(html) {
  if (!html || html.trim() === "") {
    return null;
  }
  
  // Clean up empty Tiptap elements
  let cleanedHtml = html
    .replace(/<p><br><\/p>/gi, "")
    .replace(/<p><\/p>/gi, "")
    .replace(/<span><\/span>/gi, "")
    .trim();
  
  // If already has proper structure, return as-is
  if (cleanedHtml.includes("<!DOCTYPE html>") || (cleanedHtml.includes("<html") && cleanedHtml.includes("<body"))) {
    return cleanedHtml;
  }
  
  // Wrap with email-friendly structure
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;font-family:Arial,sans-serif;">
  ${cleanedHtml}
</body>
</html>`;
}

router.post("/seed", authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const [templateResults, audiences] = await Promise.all([
      seedCampaignTemplates(),
      createDefaultAudiences(),
    ]);
    res.json({ success: true, ...templateResults, audiencesCreated: audiences.length });
  } catch (err) {
    console.error("Seed error:", err);
    res.status(500).json({ error: "Seed failed" });
  }
});

router.get("/templates", authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { phase, audience, status } = req.query;
    const filter = {};
    
    if (phase) filter.phase = phase;
    if (audience) filter.audience = audience;
    if (status) filter.status = status;

    const templates = await CampaignTemplate.find(filter)
      .sort({ sendDate: 1, audience: 1 });

    const stats = {
      total: templates.length,
      pending: templates.filter(t => t.status === "pending").length,
      sent: templates.filter(t => t.status === "sent").length,
      draft: templates.filter(t => t.status === "draft").length,
    };

    res.json({ templates, stats });
  } catch (err) {
    console.error("Fetch templates error:", err);
    res.status(500).json({ error: "Server error" });
  }
});

router.get("/templates/:id", authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const template = await CampaignTemplate.findById(req.params.id);
    if (!template) {
      return res.status(404).json({ error: "Template not found" });
    }
    res.json(template);
  } catch (err) {
    res.status(500).json({ error: "Server error" });
  }
});

router.post("/templates", authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { phase, audience, subject, purpose, sendDate } = req.body;

    if (!phase || !audience || !subject || !purpose || !sendDate) {
      return res.status(400).json({ error: "Missing required fields: phase, audience, subject, purpose, sendDate" });
    }

    const templateId = `manual-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

    const template = new CampaignTemplate({
      templateId,
      phase,
      audience,
      subject,
      purpose,
      sendDate: new Date(sendDate),
      bodySummary: "Click to edit campaign content",
      ctaText: "Learn More",
      ctaLink: "www.thetechfestival.com",
      segment: "All contacts",
      status: "pending",
      autoGenerated: false,
    });

    await template.save();
    res.json(template);
  } catch (err) {
    console.error("Create template error:", err);
    res.status(500).json({ error: "Failed to create campaign" });
  }
});

router.delete("/templates/:id", authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const template = await CampaignTemplate.findById(req.params.id);
    if (!template) {
      return res.status(404).json({ error: "Template not found" });
    }

    await CampaignTemplate.findByIdAndDelete(req.params.id);
    res.json({ success: true, message: "Campaign deleted" });
  } catch (err) {
    console.error("Delete template error:", err);
    res.status(500).json({ error: "Failed to delete campaign" });
  }
});

router.put("/templates/:id", authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { subject, bodySummary, ctaText, ctaLink, status, sendDate, htmlBody, textBody } = req.body;
    
    const template = await CampaignTemplate.findById(req.params.id);
    if (!template) {
      return res.status(404).json({ error: "Template not found" });
    }

    if (subject) template.subject = subject;
    if (bodySummary) template.bodySummary = bodySummary;
    if (ctaText) template.ctaText = ctaText;
    if (ctaLink) template.ctaLink = ctaLink;
    if (status) template.status = status;
    if (sendDate) template.sendDate = new Date(sendDate);
    if (htmlBody !== undefined) template.htmlBody = htmlBody;
    if (textBody !== undefined) template.textBody = textBody;

    await template.save();
    res.json(template);
  } catch (err) {
    console.error("Update template error:", err);
    res.status(500).json({ error: "Server error" });
  }
});

router.post("/templates/:id/send", authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { subject, htmlBody, textBody, audienceId } = req.body;
    const template = await CampaignTemplate.findById(req.params.id);
    if (!template) {
      return res.status(404).json({ error: "Template not found" });
    }

    let audience;
    if (audienceId) {
      audience = await Audience.findById(audienceId);
      if (!audience) {
        return res.status(400).json({ error: "Audience not found" });
      }
    } else {
      const audienceMap = {
        "Sponsors": "Sponsor Leads",
        "Exhibitors": "Exhibitor Leads",
        "Delegates": "Delegate Prospects",
        "Visitors": "Visitor Prospects",
      };
      const audienceName = audienceMap[template.audience];
      audience = await Audience.findOne({ name: audienceName });
    }

    if (!audience || audience.contacts.length === 0) {
      return res.status(400).json({ error: `No contacts in the selected audience` });
    }

    const finalSubject = subject || template.subject;
    let html = htmlBody || template.htmlBody;
    
    if (!html) {
      html = generateEmailHtml(template);
    }

    // Validate template before sending
    const wrappedHtml = wrapEmailHtml(html);
    if (!wrappedHtml) {
      return res.status(400).json({ error: "Email template is empty. Please add content and save the template before sending." });
    }
    console.log(`[AUTOMATION SEND] Template "${template.subject}" validated, length: ${wrappedHtml.length}`);

    const trackingRecords = [];
    const templateIdStr = template._id.toString();
    const campaignIdPrefix = `tpl-${templateIdStr}`;
    
    const emailPromises = audience.contacts.map((contact) => {
      try {
        console.log(`[AUTOMATION] Processing contact: ${contact.email}`);
        console.log(`[AUTOMATION] Contact data:`, { firstName: contact.firstName, lastName: contact.lastName, company: contact.company });
        
        const personalizedHtml = wrappedHtml
          .replace(/\{\{name\}\}/g, contact.name || contact.email.split("@")[0])
          .replace(/\{\{email\}\}/g, contact.email)
          .replace(/\/firstname/gi, contact.firstName || contact.name || contact.email.split("@")[0])
          .replace(/\/lastname/gi, contact.lastName || "")
          .replace(/\/company/gi, contact.company || "")
          .replace(/\/title/gi, contact.title || "")
          .replace(/\/location/gi, contact.location || "");

        console.log(`[AUTOMATION] Personalized HTML sample:`, personalizedHtml.substring(0, 300));

        const htmlWithLinksTracked = wrapLinksWithTracking(
          personalizedHtml,
          campaignIdPrefix,
          contact.email,
          API_URL
        );

        const trackingPixel = `<img src="${API_URL}/api/track/open/${campaignIdPrefix}/${encodeURIComponent(contact.email)}" width="1" height="1" style="display:none" alt="" />`;

        const tracking = new EmailTracking({
          campaignId: campaignIdPrefix,
          email: contact.email,
          status: "pending",
        });
        trackingRecords.push(tracking.save());

        return sendCampaignEmail({
          to: contact.email,
          subject: finalSubject,
          html: htmlWithLinksTracked + trackingPixel,
          campaignId: campaignIdPrefix,
          recipientEmail: contact.email,
          text: textBody || template.textBody,
        });
      } catch (err) {
        console.error(`Error sending to ${contact.email}:`, err);
        return Promise.resolve({ success: false, error: err.message });
      }
    });

    await Promise.allSettled(emailPromises);
    await Promise.all(trackingRecords);

    const sentCount = audience.contacts.length;

    if (subject) template.subject = subject;
    if (htmlBody) template.htmlBody = htmlBody;
    if (textBody) template.textBody = textBody;
    template.status = "sent";
    template.sentAt = new Date();
    await template.save();

    const campaignName = campaignIdPrefix;
    let campaign = await Campaign.findOne({ name: campaignName });
    if (!campaign) {
      const audienceDoc = await Audience.findOne({ name: audienceName });
      campaign = new Campaign({
        name: campaignName,
        subject: finalSubject,
        audienceId: audienceDoc?._id || null,
        template: html,
        status: "sent",
        sentAt: new Date(),
        stats: {
          sent: sentCount,
          uniqueOpens: 0,
          totalOpens: 0,
          uniqueClicks: 0,
          totalClicks: 0,
          bounces: 0,
          hardBounces: 0,
          softBounces: 0,
          unsubscribes: 0,
        },
        createdBy: req.user?.userId,
      });
    } else {
      campaign.stats.sent = sentCount;
      campaign.status = "sent";
      campaign.sentAt = new Date();
    }
    await campaign.save();

    template.campaign = campaign._id;
    await template.save();

    console.log(`[AUTOMATION CAMPAIGN] Template "${template.templateId}" sent to ${sentCount} recipients via audience "${audienceName}"`);
    console.log(`[AUTOMATION CAMPAIGN] Campaign entry created/updated: "${campaign.name}" (ID: ${campaign._id}), stats.sent=${sentCount}`);

    res.json({ success: true, sent: sentCount, template, campaignId: campaign._id });
  } catch (err) {
    console.error("Send template error:", err);
    console.error("Error stack:", err.stack);
    res.status(500).json({ error: "Failed to send", details: err.message });
  }
});

router.get("/calendar", authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const templates = await CampaignTemplate.find().sort({ sendDate: 1 });

    const calendar = {};
    const phases = ["Phase 1", "Phase 2", "Phase 3", "Phase 4", "Phase 5"];
    const audiences = ["Sponsors", "Exhibitors", "Delegates", "Visitors"];

    for (const phase of phases) {
      calendar[phase] = {};
      for (const audience of audiences) {
        calendar[phase][audience] = [];
      }
    }

    for (const t of templates) {
      if (calendar[t.phase] && calendar[t.phase][t.audience]) {
        calendar[t.phase][t.audience].push({
          id: t._id,
          templateId: t.templateId,
          sendDate: t.sendDate,
          subject: t.subject,
          purpose: t.purpose,
          status: t.status,
          sentAt: t.sentAt,
          htmlBody: t.htmlBody || null,
          textBody: t.textBody || null,
        });
      }
    }

    res.json({ calendar, phases, audiences });
  } catch (err) {
    res.status(500).json({ error: "Server error" });
  }
});

router.get("/upcoming", authMiddleware, adminMiddleware, async (req, res) => {
  try {
    const { days = 7 } = req.query;
    const now = new Date();
    const future = new Date();
    future.setDate(future.getDate() + parseInt(days));

    const templates = await CampaignTemplate.find({
      sendDate: { $gte: now, $lte: future },
      status: "pending",
    }).sort({ sendDate: 1, audience: 1 });

    res.json(templates);
  } catch (err) {
    res.status(500).json({ error: "Server error" });
  }
});

function generateEmailHtml(template) {
  const ctaFullLink = template.ctaLink.startsWith("http") 
    ? template.ctaLink 
    : `https://${template.ctaLink}`;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background-color:#f4f0ff;font-family:Arial,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:20px;">
    <div style="background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);">
      <div style="background:linear-gradient(135deg,#7a3fd1,#f5a623);padding:40px 30px;text-align:center;">
        <h1 style="color:white;margin:0;font-size:24px;">The Tech Festival Canada 2026</h1>
        <p style="color:rgba(255,255,255,0.9);margin:10px 0 0;font-size:14px;">October 26-27, 2026 • Toronto, ON</p>
      </div>
      
      <div style="padding:40px 30px;">
        <p style="color:#333;font-size:16px;line-height:1.6;">
          ${template.bodySummary}
        </p>
        
        <div style="text-align:center;margin:30px 0;">
          <a href="${ctaFullLink}" style="display:inline-block;background:linear-gradient(135deg,#7a3fd1,#f5a623);color:white;padding:16px 32px;border-radius:50px;text-decoration:none;font-weight:bold;font-size:16px;">
            ${template.ctaText} →
          </a>
        </div>
        
        <div style="background:#f9f5ff;border-radius:8px;padding:20px;margin-top:30px;">
          <p style="margin:0;color:#666;font-size:12px;text-transform:uppercase;letter-spacing:1px;">Campaign Info</p>
          <p style="margin:5px 0 0;color:#333;font-size:14px;">
            <strong>Phase:</strong> ${template.phase} | 
            <strong>Audience:</strong> ${template.audience} | 
            <strong>Purpose:</strong> ${template.purpose}
          </p>
        </div>
      </div>
      
      <div style="background:#1a1035;padding:30px;text-align:center;">
        <p style="color:rgba(255,255,255,0.6);font-size:12px;margin:0;">
          The Tech Festival Canada • Toronto, Ontario
        </p>
        <p style="color:rgba(255,255,255,0.4);font-size:11px;margin:10px 0 0;">
          <a href="#" style="color:rgba(255,255,255,0.5);">Unsubscribe</a> | 
          <a href="#" style="color:rgba(255,255,255,0.5);">View in browser</a>
        </p>
      </div>
    </div>
  </div>
</body>
</html>
  `;
}

export default router;
