import mongoose from "mongoose";

const campaignTemplateSchema = new mongoose.Schema({
  templateId: {
    type: String,
    required: true,
    unique: true,
  },
  sendDate: {
    type: Date,
    required: true,
  },
  phase: {
    type: String,
    enum: ["Phase 1", "Phase 2", "Phase 3", "Phase 4", "Phase 5"],
    required: true,
  },
  audience: {
    type: String,
    enum: ["Sponsors", "Exhibitors", "Delegates", "Visitors"],
    required: true,
  },
  subject: {
    type: String,
    required: true,
  },
  purpose: {
    type: String,
    required: true,
  },
  bodySummary: {
    type: String,
    required: true,
  },
  ctaText: {
    type: String,
    required: true,
  },
  ctaLink: {
    type: String,
    required: true,
  },
  segment: {
    type: String,
    required: true,
  },
  autoGenerated: {
    type: Boolean,
    default: false,
  },
  campaign: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Campaign",
  },
  sentAt: Date,
  htmlBody: {
    type: String,
  },
  textBody: {
    type: String,
  },
  status: {
    type: String,
    enum: ["pending", "draft", "scheduled", "sent", "skipped"],
    default: "pending",
  },
}, {
  timestamps: true,
});

campaignTemplateSchema.index({ sendDate: 1, audience: 1 });
campaignTemplateSchema.index({ phase: 1, audience: 1 });

export default mongoose.model("CampaignTemplate", campaignTemplateSchema);
